gsc -keep-temp -exe -o wsServer wsServer.c base64.c sha1.c ws.c handshake.c utf8.c main.scm 
gcc  -O1 -fexpensive-optimizations -fno-gcse    -Wno-unused -Wno-write-strings -Wdisabled-optimization -fwrapv -fno-strict-aliasing -fno-trapping-math -fno-math-errno -fschedule-insns2 -fomit-frame-pointer -fipa-ra -fmove-loop-invariants -march=x86-64 -fPIC -fno-common -mpc64   -D___SINGLE_HOST -D___CAN_IMPORT_CLIB_DYNAMICALLY -D___CAN_IMPORT_SETJMP_DYNAMICALLY  -I"/usr/local/Gambit/include" -c -o 'wsServer.o'  'wsServer.c'
gcc  -O1 -fexpensive-optimizations -fno-gcse    -Wno-unused -Wno-write-strings -Wdisabled-optimization -fwrapv -fno-strict-aliasing -fno-trapping-math -fno-math-errno -fschedule-insns2 -fomit-frame-pointer -fipa-ra -fmove-loop-invariants -march=x86-64 -fPIC -fno-common -mpc64   -D___SINGLE_HOST -D___CAN_IMPORT_CLIB_DYNAMICALLY -D___CAN_IMPORT_SETJMP_DYNAMICALLY  -I"/usr/local/Gambit/include" -c -o 'base64.o'  'base64.c'
gcc  -O1 -fexpensive-optimizations -fno-gcse    -Wno-unused -Wno-write-strings -Wdisabled-optimization -fwrapv -fno-strict-aliasing -fno-trapping-math -fno-math-errno -fschedule-insns2 -fomit-frame-pointer -fipa-ra -fmove-loop-invariants -march=x86-64 -fPIC -fno-common -mpc64   -D___SINGLE_HOST -D___CAN_IMPORT_CLIB_DYNAMICALLY -D___CAN_IMPORT_SETJMP_DYNAMICALLY  -I"/usr/local/Gambit/include" -c -o 'sha1.o'  'sha1.c'
gcc  -O1 -fexpensive-optimizations -fno-gcse    -Wno-unused -Wno-write-strings -Wdisabled-optimization -fwrapv -fno-strict-aliasing -fno-trapping-math -fno-math-errno -fschedule-insns2 -fomit-frame-pointer -fipa-ra -fmove-loop-invariants -march=x86-64 -fPIC -fno-common -mpc64   -D___SINGLE_HOST -D___CAN_IMPORT_CLIB_DYNAMICALLY -D___CAN_IMPORT_SETJMP_DYNAMICALLY  -I"/usr/local/Gambit/include" -c -o 'ws.o'  'ws.c'
gcc  -O1 -fexpensive-optimizations -fno-gcse    -Wno-unused -Wno-write-strings -Wdisabled-optimization -fwrapv -fno-strict-aliasing -fno-trapping-math -fno-math-errno -fschedule-insns2 -fomit-frame-pointer -fipa-ra -fmove-loop-invariants -march=x86-64 -fPIC -fno-common -mpc64   -D___SINGLE_HOST -D___CAN_IMPORT_CLIB_DYNAMICALLY -D___CAN_IMPORT_SETJMP_DYNAMICALLY  -I"/usr/local/Gambit/include" -c -o 'handshake.o'  'handshake.c'
gcc  -O1 -fexpensive-optimizations -fno-gcse    -Wno-unused -Wno-write-strings -Wdisabled-optimization -fwrapv -fno-strict-aliasing -fno-trapping-math -fno-math-errno -fschedule-insns2 -fomit-frame-pointer -fipa-ra -fmove-loop-invariants -march=x86-64 -fPIC -fno-common -mpc64   -D___SINGLE_HOST -D___CAN_IMPORT_CLIB_DYNAMICALLY -D___CAN_IMPORT_SETJMP_DYNAMICALLY  -I"/usr/local/Gambit/include" -c -o 'utf8.o'  'utf8.c'
gcc  -O1 -fexpensive-optimizations -fno-gcse    -Wno-unused -Wno-write-strings -Wdisabled-optimization -fwrapv -fno-strict-aliasing -fno-trapping-math -fno-math-errno -fschedule-insns2 -fomit-frame-pointer -fipa-ra -fmove-loop-invariants -march=x86-64 -fPIC -fno-common -mpc64   -D___SINGLE_HOST -D___CAN_IMPORT_CLIB_DYNAMICALLY -D___CAN_IMPORT_SETJMP_DYNAMICALLY  -I"/usr/local/Gambit/include" -c -o 'main.o'  'main.c'
gcc  -O1 -fexpensive-optimizations -fno-gcse    -Wno-unused -Wno-write-strings -Wdisabled-optimization -fwrapv -fno-strict-aliasing -fno-trapping-math -fno-math-errno -fschedule-insns2 -fomit-frame-pointer -fipa-ra -fmove-loop-invariants -march=x86-64 -fPIC -fno-common -mpc64   -D___SINGLE_HOST -D___CAN_IMPORT_CLIB_DYNAMICALLY -D___CAN_IMPORT_SETJMP_DYNAMICALLY  -I"/usr/local/Gambit/include" -c -o 'main_.o'  'main_.c'
gcc     -Wno-unused -Wno-write-strings -Wdisabled-optimization -fwrapv -fno-strict-aliasing -fno-trapping-math -fno-math-errno -fschedule-insns2 -fomit-frame-pointer -fipa-ra -fmove-loop-invariants -march=x86-64 -fPIC -fno-common -mpc64    -Wno-unused -Wno-write-strings -Wdisabled-optimization -fwrapv -fno-strict-aliasing -fno-trapping-math -fno-math-errno -fschedule-insns2 -fomit-frame-pointer -fipa-ra -fmove-loop-invariants -march=x86-64 -fPIC -fno-common -mpc64   -rdynamic  -D___SINGLE_HOST -D___CAN_IMPORT_CLIB_DYNAMICALLY -D___CAN_IMPORT_SETJMP_DYNAMICALLY  -I"/usr/local/Gambit/include"  -o 'wsServer'   'main_.o' 'wsServer.o' 'base64.o' 'sha1.o' 'ws.o' 'handshake.o' 'utf8.o' 'main.o' "/usr/local/Gambit/lib/libgambit.a" -lm 
